### ISSUE TITLE
代码上传不全？

### ISSUE THREAD

**Issue by LH-Liu** [duzexu/Use-Unity-as-Library#1]
无法运行，如图
<img width="340" alt="屏幕快照 2020-07-22 上午11 20 54" src="https://user-images.githubusercontent.com/14884787/88130558-74890780-cc0d-11ea-99a0-a227aa10a9ce.png">

**Comment by duzexu** [comment]
需要先用Unity导出工程
参考https://duzexu.github.io/post/Use_Unity_as_Library/ 集成步骤部分

**Comment by LH-Liu** [comment]
> 需要先用Unity导出工程
> 参考https://duzexu.github.io/post/Use_Unity_as_Library/ 集成步骤部分

嗯嗯，操作成功了。感谢分享
